// Marcus Aurelius, Meditations, George Long translation (public domain).
// One line a day via pickForDay() in lib/life.ts. [text, book.section]
export const MEDITATIONS: readonly (readonly [string, string])[] = [
  ["Begin the morning by saying to thyself, I shall meet with the busy-body, the ungrateful, arrogant, deceitful, envious, unsocial.", "II.1"],
  ["A limit of time is fixed for thee, which if thou dost not use for clearing away the clouds from thy mind, it will go and thou wilt go, and it will never return.", "II.4"],
  ["Every moment think steadily as a Roman and a man to do what thou hast in hand with perfect and simple dignity.", "II.5"],
  ["Do every act of thy life as if it were the last.", "II.5"],
  ["Since it is possible that thou mayest depart from life this very moment, regulate every act and thought accordingly.", "II.11"],
  ["Though thou shouldst be going to live three thousand years, and as many times ten thousand years, still remember that no man loses any other life than this which he now lives.", "II.14"],
  ["Remember that all is opinion.", "II.15"],
  ["A man then must stand erect, not be kept erect by others.", "III.5"],
  ["Never value anything as profitable to thyself which shall compel thee to break thy promise, to lose thy self-respect.", "III.7"],
  ["It is in thy power whenever thou shalt choose to retire into thyself. For nowhere either with more quiet or more freedom from trouble does a man retire than into his own soul.", "IV.3"],
  ["The universe is transformation: life is opinion.", "IV.3"],
  ["Take away thy opinion, and then there is taken away the complaint, \"I have been harmed.\" Take away the complaint, \"I have been harmed,\" and the harm is taken away.", "IV.7"],
  ["Do not act as if thou wert going to live ten thousand years. Death hangs over thee. While thou livest, while it is in thy power, be good.", "IV.17"],
  ["How much trouble he avoids who does not look to see what his neighbour says or does or thinks, but only to what he does himself, that it may be just and pure.", "IV.18"],
  ["Everything which is in any way beautiful is beautiful in itself, and terminates in itself, not having praise as part of itself.", "IV.20"],
  ["Everything harmonizes with me, which is harmonious to thee, O Universe. Nothing for me is too early nor too late, which is in due time for thee.", "IV.23"],
  ["Occupy thyself with few things, says the philosopher, if thou wouldst be tranquil.", "IV.24"],
  ["Love the art, poor as it may be, which thou hast learned, and be content with it.", "IV.31"],
  ["Observe constantly that all things take place by change.", "IV.36"],
  ["Time is like a river made up of the events which happen, and a violent stream; for as soon as a thing has been seen, it is carried away, and another comes in its place, and this will be carried away too.", "IV.43"],
  ["Be like the promontory against which the waves continually break, but it stands firm and tames the fury of the water around it.", "IV.49"],
  ["In the morning when thou risest unwillingly, let this thought be present: I am rising to the work of a human being.", "V.1"],
  ["Judge every word and deed which are according to nature to be fit for thee.", "V.3"],
  ["Such as are thy habitual thoughts, such also will be the character of thy mind; for the soul is dyed by the thoughts.", "V.16"],
  ["Where a man can live, there he can also live well.", "V.16"],
  ["Nothing happens to any man which he is not formed by nature to bear.", "V.18"],
  ["Let it make no difference to thee whether thou art cold or warm, if thou art doing thy duty.", "VI.2"],
  ["Look within. Let neither the peculiar quality of anything nor its value escape thee.", "VI.3"],
  ["The best way of avenging thyself is not to become like the wrong doer.", "VI.6"],
  ["If a thing is difficult to be accomplished by thyself, do not think that it is impossible for man: but if anything is possible for man and conformable to his nature, think that this can be attained by thyself too.", "VI.19"],
  ["If any man is able to convince me and show me that I do not think or act right, I will gladly change; for I seek the truth, by which no man was ever injured.", "VI.21"],
  ["I do my duty: other things trouble me not.", "VI.22"],
  ["Adapt thyself to the things with which thy lot has been cast: and the men among whom thou hast received thy portion, love them, but do it truly, sincerely.", "VI.39"],
  ["That which is not good for the swarm, neither is it good for the bee.", "VI.54"],
  ["Be not ashamed to be helped; for it is thy business to do thy duty like a soldier in the assault on a town.", "VII.7"],
  ["Let not future things disturb thee, for thou wilt come to them, if it shall be necessary, having with thee the same reason which now thou usest for present things.", "VII.8"],
  ["Whatever any one does or says, I must be good, just as if the gold, or the emerald, or the purple were always saying this, Whatever any one does or says, I must be emerald and keep my colour.", "VII.15"],
  ["Think not so much of what thou hast not as of what thou hast.", "VII.27"],
  ["It is not right to vex ourselves at things, for they care nought about it.", "VII.38"],
  ["No man can escape his destiny, the next inquiry being how he may best live the time that he has to live.", "VII.46"],
  ["Look within. Within is the fountain of good, and it will ever bubble up, if thou wilt ever dig.", "VII.59"],
  ["The art of life is more like the wrestler's art than the dancer's, in respect of this, that it should stand ready and firm to meet onsets which are sudden and unexpected.", "VII.61"],
  ["Very little indeed is necessary for living a happy life.", "VII.67"],
  ["The perfection of moral character consists in this, in passing every day as the last, and in being neither violently excited nor torpid nor playing the hypocrite.", "VII.69"],
  ["It is a ridiculous thing for a man not to fly from his own badness, which is indeed possible, but to fly from other men's badness, which is impossible.", "VII.71"],
  ["Attend to the matter which is before thee, whether it is an opinion or an act or a word.", "VIII.22"],
  ["Speak both in the senate and to every man, whoever he may be, appropriately, not with any affectation: use plain discourse.", "VIII.30"],
  ["Receive wealth or prosperity without arrogance; and be ready to let it go.", "VIII.33"],
  ["Do not disturb thyself by thinking of the whole of thy life.", "VIII.36"],
  ["If thou art pained by any external thing, it is not this thing that disturbs thee, but thy own judgment about it. And it is in thy power to wipe out this judgment now.", "VIII.47"],
  ["The mind which is free from passions is a citadel, for man has nothing more secure to which he can fly for refuge.", "VIII.48"],
  ["Neither in thy actions be sluggish nor in thy conversation without method, nor wandering in thy thoughts.", "VIII.51"],
  ["Men exist for the sake of one another. Teach them then or bear with them.", "VIII.59"],
  ["He who does wrong does wrong against himself.", "IX.4"],
  ["He often acts unjustly who does not do a certain thing; not only he who does a certain thing.", "IX.5"],
  ["To-day I have got out of all trouble, or rather I have cast out all trouble, for it was not outside, but within and in my opinions.", "IX.13"],
  ["Do not expect Plato's Republic: but be content if the smallest thing goes on well.", "IX.29"],
  ["Loss is nothing else than change.", "IX.35"],
  ["No longer talk at all about the kind of man that a good man ought to be, but be such.", "X.16"],
  ["I have often wondered how it is that every man loves himself more than all the rest of men, but yet sets less value on his own opinion of himself than on the opinion of others.", "XII.4"],
  ["How ridiculous and what a stranger he is who is surprised at anything which happens in life.", "XII.13"],
  ["If it is not right, do not do it: if it is not true, do not say it.", "XII.17"],
  ["Consider that everything is opinion, and opinion is in thy power.", "XII.22"],
];
